In [1]:
# hide GPU from tensorflow
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

In [1]:
import random
import numpy as np
import tensorflow as tf
import mlflow.keras

from ml_investing_wne import config
from ml_investing_wne.utils import get_logger
from ml_investing_wne.experiment_factory import create_asset, experiment_factory

random.seed(config.seed)
np.random.seed(config.seed)
tf.random.set_seed(config.seed)


In [2]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [3]:
config.currency = 'BTCUSDT'
btc = create_asset()
experiment_btc = experiment_factory(btc).get_experiment()
experiment_btc.train_test_val_split()

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2023-08-10 17:17:22.631496: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-08-10 17:17:22.966078: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at strided_slice_op.cc:111 : INVALID_ARGUMENT: slice index 96 of dimension 0 out of bounds.
2023-08-10 17:17:22.966240: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at strided_slice_op.cc:111 : INVALID_ARGUMENT: slice index 96 of dimension 0 out of bounds.
2023-08-10 17:17:22.966342: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at strided_slice_op.cc:111 : INVALID_ARGUMENT: slice index 96 of dimension 0 out of bounds.
2023-08-10 17:17:22.966510: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at strided_slice_op.cc:111 : INVALID_ARGUMENT: slice index 96 of dimension 0 out of bounds.
2023-08-10 17:17:22.966604: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at strided_slice_op.cc:111 : INVALID_ARGUM

InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} slice index 96 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]] [Op:IteratorGetNext]

In [4]:
experiment_btc.df.head(10)


open     close      high       low        volume  \
datetime                                                                    
2018-01-26 12:00:00   10510.0   11089.0   11399.0   10410.0  15119.064234   
2018-01-27 00:00:00   11089.0   11020.0   11400.0  10842.69   9190.499299   
2018-01-27 12:00:00   11018.0   11491.0   11650.0  10968.18   9670.269046   
2018-01-28 00:00:00  11499.98  12012.62   12244.0   11408.0  10060.951174   
2018-01-28 12:00:00  12001.94  11879.95   12079.9   11652.0   6826.388350   
2018-01-29 00:00:00  11879.95  11279.99  11975.02  11139.55   9258.759356   
2018-01-29 12:00:00  11272.01   11251.0   11499.0   11150.0   4911.618182   
2018-01-30 00:00:00  11250.11  11047.34  11308.42   10850.0   6459.968361   
2018-01-30 12:00:00  11050.34  10237.51   11096.0    9900.0  19094.404585   
2018-01-31 00:00:00   10230.0  10290.05   10363.0    9700.0  12092.427593   

                    y_pred  to_keep      SMA_5         EMA_5         VAR_5  \
datetime                                                                     
2018-01-26 12:00:00      1        1  11068.646  10988.995757  105005.59183   
2018-01-27 00:00:00      1        1  11002.648  10999.330504   80363.91857   
2018-01-27 12:00:00      1        1  11057.848  11163.220336  124903.69457   
2018-01-28 00:00:00      0        1  11225.318  11446.353558  314296.35492   
2018-01-28 12:00:00      0        1  11498.514  11590.885705  201633.05648   
2018-01-29 00:00:00      0        1  11536.712  11487.253803  169821.95307   
2018-01-29 12:00:00      0        0  11582.912  11408.502536  120813.91707   
2018-01-30 00:00:00      0        1  11494.180  11288.115024  180569.59515   
2018-01-30 12:00:00      0        1  11139.158  10937.913349  350628.68337   
2018-01-31 00:00:00      0        1  10821.178  10721.958899  267292.48497   

                     ...     BBU_5_2.0  BBB_5_2.0  BBP_5_2.0     roc_1  hour  \
datetime             ...                                                       
2018-01-26 12:00:00  ...  11648.316505  10.474100   0.517557  0.054692    12   
2018-01-27 00:00:00  ...  11509.761931   9.218034   0.517109 -0.006222     0   
2018-01-27 12:00:00  ...  11690.059849  11.434627   0.842569   0.04274    12   
2018-01-28 00:00:00  ...  12228.188049  17.868002   0.892524  0.045394     0   
2018-01-28 12:00:00  ...  12301.773473  13.971535    0.73743 -0.011044    12   
2018-01-29 00:00:00  ...  12273.889217  12.779676   0.325875 -0.050502     0   
2018-01-29 12:00:00  ...  12204.687309  10.736079   0.233093  -0.00257    12   
2018-01-30 00:00:00  ...  12254.326502  13.226633   0.206083 -0.018102     0   
2018-01-30 12:00:00  ...  12198.408578  19.018504   0.074393 -0.073305    12   
2018-01-31 00:00:00  ...  11746.021745  17.093217   0.212855  0.005132     0   

                     weekday      hour_sin  hour_cos   weekday_sin  \
datetime                                                             
2018-01-26 12:00:00        4 -2.449294e-16       1.0 -8.660254e-01   
2018-01-27 00:00:00        5  0.000000e+00       1.0 -8.660254e-01   
2018-01-27 12:00:00        5 -2.449294e-16       1.0 -8.660254e-01   
2018-01-28 00:00:00        6  0.000000e+00       1.0 -2.449294e-16   
2018-01-28 12:00:00        6 -2.449294e-16       1.0 -2.449294e-16   
2018-01-29 00:00:00        0  0.000000e+00       1.0  0.000000e+00   
2018-01-29 12:00:00        0 -2.449294e-16       1.0  0.000000e+00   
2018-01-30 00:00:00        1  0.000000e+00       1.0  8.660254e-01   
2018-01-30 12:00:00        1 -2.449294e-16       1.0  8.660254e-01   
2018-01-31 00:00:00        2  0.000000e+00       1.0  8.660254e-01   

                     weekday_cos  
datetime                          
2018-01-26 12:00:00         -0.5  
2018-01-27 00:00:00          0.5  
2018-01-27 12:00:00          0.5  
2018-01-28 00:00:00          1.0  
2018-01-28 12:00:00          1.0  
2018-01-29 00:00:00          1.0  
2018-01-29 12:00:00          1.0  
2018-01-30 00:00:00          0.5  
2018-01-30 

In [5]:
# experiment_btc.df['y_pred'] = [1 if y > 1 else 0 for y in  experiment_btc.df['y_pred']]
# experiment_btc.df.dropna(inplace=True)
train_examples = experiment_btc.df.drop(columns=['y_pred']).values
train_labels = experiment_btc.df['y_pred'].values

In [6]:
date_index = experiment_btc.df.reset_index()
date_index.reset_index(inplace=True)
date_index = date_index[['index', 'datetime']]
date_index

index            datetime
0         0 2018-01-26 12:00:00
1         1 2018-01-27 00:00:00
2         2 2018-01-27 12:00:00
3         3 2018-01-28 00:00:00
4         4 2018-01-28 12:00:00
...     ...                 ...
3932   3932 2023-06-15 12:00:00
3933   3933 2023-06-16 00:00:00
3934   3934 2023-06-16 12:00:00
3935   3935 2023-06-17 00:00:00
3936   3936 2023-06-17 12:00:00

[3937 rows x 2 columns]

In [7]:
experiment_btc.df.head(10)

open     close      high       low        volume  \
datetime                                                                    
2018-01-26 12:00:00   10510.0   11089.0   11399.0   10410.0  15119.064234   
2018-01-27 00:00:00   11089.0   11020.0   11400.0  10842.69   9190.499299   
2018-01-27 12:00:00   11018.0   11491.0   11650.0  10968.18   9670.269046   
2018-01-28 00:00:00  11499.98  12012.62   12244.0   11408.0  10060.951174   
2018-01-28 12:00:00  12001.94  11879.95   12079.9   11652.0   6826.388350   
2018-01-29 00:00:00  11879.95  11279.99  11975.02  11139.55   9258.759356   
2018-01-29 12:00:00  11272.01   11251.0   11499.0   11150.0   4911.618182   
2018-01-30 00:00:00  11250.11  11047.34  11308.42   10850.0   6459.968361   
2018-01-30 12:00:00  11050.34  10237.51   11096.0    9900.0  19094.404585   
2018-01-31 00:00:00   10230.0  10290.05   10363.0    9700.0  12092.427593   

                    y_pred  to_keep      SMA_5         EMA_5         VAR_5  \
datetime                                                                     
2018-01-26 12:00:00      1        1  11068.646  10988.995757  105005.59183   
2018-01-27 00:00:00      1        1  11002.648  10999.330504   80363.91857   
2018-01-27 12:00:00      1        1  11057.848  11163.220336  124903.69457   
2018-01-28 00:00:00      0        1  11225.318  11446.353558  314296.35492   
2018-01-28 12:00:00      0        1  11498.514  11590.885705  201633.05648   
2018-01-29 00:00:00      0        1  11536.712  11487.253803  169821.95307   
2018-01-29 12:00:00      0        0  11582.912  11408.502536  120813.91707   
2018-01-30 00:00:00      0        1  11494.180  11288.115024  180569.59515   
2018-01-30 12:00:00      0        1  11139.158  10937.913349  350628.68337   
2018-01-31 00:00:00      0        1  10821.178  10721.958899  267292.48497   

                     ...     BBU_5_2.0  BBB_5_2.0  BBP_5_2.0     roc_1  hour  \
datetime             ...                                                       
2018-01-26 12:00:00  ...  11648.316505  10.474100   0.517557  0.054692    12   
2018-01-27 00:00:00  ...  11509.761931   9.218034   0.517109 -0.006222     0   
2018-01-27 12:00:00  ...  11690.059849  11.434627   0.842569   0.04274    12   
2018-01-28 00:00:00  ...  12228.188049  17.868002   0.892524  0.045394     0   
2018-01-28 12:00:00  ...  12301.773473  13.971535    0.73743 -0.011044    12   
2018-01-29 00:00:00  ...  12273.889217  12.779676   0.325875 -0.050502     0   
2018-01-29 12:00:00  ...  12204.687309  10.736079   0.233093  -0.00257    12   
2018-01-30 00:00:00  ...  12254.326502  13.226633   0.206083 -0.018102     0   
2018-01-30 12:00:00  ...  12198.408578  19.018504   0.074393 -0.073305    12   
2018-01-31 00:00:00  ...  11746.021745  17.093217   0.212855  0.005132     0   

                     weekday      hour_sin  hour_cos   weekday_sin  \
datetime                                                             
2018-01-26 12:00:00        4 -2.449294e-16       1.0 -8.660254e-01   
2018-01-27 00:00:00        5  0.000000e+00       1.0 -8.660254e-01   
2018-01-27 12:00:00        5 -2.449294e-16       1.0 -8.660254e-01   
2018-01-28 00:00:00        6  0.000000e+00       1.0 -2.449294e-16   
2018-01-28 12:00:00        6 -2.449294e-16       1.0 -2.449294e-16   
2018-01-29 00:00:00        0  0.000000e+00       1.0  0.000000e+00   
2018-01-29 12:00:00        0 -2.449294e-16       1.0  0.000000e+00   
2018-01-30 00:00:00        1  0.000000e+00       1.0  8.660254e-01   
2018-01-30 12:00:00        1 -2.449294e-16       1.0  8.660254e-01   
2018-01-31 00:00:00        2  0.000000e+00       1.0  8.660254e-01   

                     weekday_cos  
datetime                          
2018-01-26 12:00:00         -0.5  
2018-01-27 00:00:00          0.5  
2018-01-27 12:00:00          0.5  
2018-01-28 00:00:00          1.0  
2018-01-28 12:00:00          1.0  
2018-01-29 00:00:00          1.0  
2018-01-29 12:00:00          1.0  
2018-01-30 00:00:00          0.5  
2018-01-30 

In [8]:
from tensorflow.keras.utils import to_categorical

In [9]:
train_examples

array([[10510.0, 11089.0, 11399.0, ..., 1.0, -0.8660254037844384,
        -0.5000000000000004],
       [11089.0, 11020.0, 11400.0, ..., 1.0, -0.8660254037844386,
        0.5000000000000001],
       [11018.0, 11491.0, 11650.0, ..., 1.0, -0.8660254037844386,
        0.5000000000000001],
       ...,
       [25474.51, 26345.0, 26518.0, ..., 1.0, -0.8660254037844384,
        -0.5000000000000004],
       [26345.01, 26507.76, 26839.99, ..., 1.0, -0.8660254037844386,
        0.5000000000000001],
       [26507.75, 26516.99, 26595.13, ..., 1.0, -0.8660254037844386,
        0.5000000000000001]], dtype=object)

In [10]:
sequence_length=5

In [11]:
train_dataset_2 = tf.keras.utils.timeseries_dataset_from_array(train_examples[:-sequence_length], targets=to_categorical(train_labels[sequence_length-1:]),
                                                            sequence_length=sequence_length, sequence_stride=1, batch_size=None)

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.float64).

In [71]:
for i, sample in enumerate(train_dataset_2):
    print(len(sample))
    print(sample[0].shape)
    if sample[0][0,5] > 11000:
        print('found')
    print(sample[1])
    break

2
(5, 41)
found
tf.Tensor([0. 1.], shape=(2,), dtype=float32)


In [74]:
for i, sample in enumerate(train_dataset_2):
    if sample[0].shape[0] != 5:
        print('i', i)
        break


In [43]:
a =list(train_dataset_2.take(3).as_numpy_iterator())
# print(len(a))
print(a[0])

(array([[ 1.47580100e+04,  1.48535300e+04,  1.46600000e+04,
         1.48200000e+04,  7.88317514e+02,  1.47524000e+04,
         1.47231707e+04,  4.22379865e+03,  1.45195770e+04,
         1.45191439e+04,  2.00180952e+05,  1.42262813e+04,
         1.43346345e+04,  3.20092987e+05,  1.40165645e+04,
         1.41947771e+04,  3.77744012e+05,  1.36303472e+04,
         1.36303472e+04,  2.75612835e+05,  3.75824654e+02,
         8.81958599e+01,  2.87628794e+02,  7.17877775e+01,
         7.43823419e+01,  7.65426702e+01,  6.51491208e+01,
         6.51070528e+01, -3.23025363e+01,  1.46361410e+04,
         1.47524000e+04,  1.48686590e+04,  1.57613680e+00,
         7.90730174e-01,  3.07759367e-03,  1.00000000e+00,
         2.00000000e+00,  2.69796771e-01,  9.62917287e-01,
         8.66025404e-01, -5.00000000e-01],
       [ 1.48479700e+04,  1.51199000e+04,  1.47449900e+04,
         1.50080700e+04,  8.22858852e+02,  1.48155340e+04,
         1.48181371e+04,  1.46832084e+04,  1.46613820e+04,
         1.4

In [80]:
test = train_dataset_2.filter(lambda x, _: x[4,0] > 15000)

In [83]:
for i, sample in enumerate(train_dataset_2):
    if i == 0:
        print(i)
print(i)

0
48107


In [84]:
for i, sample in enumerate(test):
    if i == 0:
        print(i)
print(i)

0
23293


In [90]:
tf_dataset = train_dataset_2.filter(lambda x, _: x[5,0] == 1)
        # remove the first column
tf_dataset = tf_dataset.map(lambda x,y : (x[:, 1: ], y))

In [122]:
test2 = test.map(lambda x,y : (x[:,1:], y) )

In [111]:
test_np = test2.as_numpy_iterator()
print(len(list(test_np)))


23294


In [123]:
a =list(test2.take(3).as_numpy_iterator())
print(a[0])

(array([[ 1.48535300e+04,  1.46600000e+04,  1.48200000e+04,
         7.88317514e+02,  1.47524000e+04,  1.47231707e+04,
         4.22379865e+03,  1.45195770e+04,  1.45191439e+04,
         2.00180952e+05,  1.42262813e+04,  1.43346345e+04,
         3.20092987e+05,  1.40165645e+04,  1.41947771e+04,
         3.77744012e+05,  1.36303472e+04,  1.36303472e+04,
         2.75612835e+05,  3.75824654e+02,  8.81958599e+01,
         2.87628794e+02,  7.17877775e+01,  7.43823419e+01,
         7.65426702e+01,  6.51491208e+01,  6.51070528e+01,
        -3.23025363e+01,  1.46361410e+04,  1.47524000e+04,
         1.48686590e+04,  1.57613680e+00,  7.90730174e-01,
         3.07759367e-03,  1.00000000e+00,  2.00000000e+00,
         2.69796771e-01,  9.62917287e-01,  8.66025404e-01,
        -5.00000000e-01],
       [ 1.51199000e+04,  1.47449900e+04,  1.50080700e+04,
         8.22858852e+02,  1.48155340e+04,  1.48181371e+04,
         1.46832084e+04,  1.46613820e+04,  1.46080396e+04,
         1.08343465e+05,  1.4

In [113]:
a =list(test.take(3).as_numpy_iterator())
# print(len(a))
print(a[0])

(array([[ 1.47580100e+04,  1.48535300e+04,  1.46600000e+04,
         1.48200000e+04,  7.88317514e+02,  1.47524000e+04,
         1.47231707e+04,  4.22379865e+03,  1.45195770e+04,
         1.45191439e+04,  2.00180952e+05,  1.42262813e+04,
         1.43346345e+04,  3.20092987e+05,  1.40165645e+04,
         1.41947771e+04,  3.77744012e+05,  1.36303472e+04,
         1.36303472e+04,  2.75612835e+05,  3.75824654e+02,
         8.81958599e+01,  2.87628794e+02,  7.17877775e+01,
         7.43823419e+01,  7.65426702e+01,  6.51491208e+01,
         6.51070528e+01, -3.23025363e+01,  1.46361410e+04,
         1.47524000e+04,  1.48686590e+04,  1.57613680e+00,
         7.90730174e-01,  3.07759367e-03,  1.00000000e+00,
         2.00000000e+00,  2.69796771e-01,  9.62917287e-01,
         8.66025404e-01, -5.00000000e-01],
       [ 1.48479700e+04,  1.51199000e+04,  1.47449900e+04,
         1.50080700e+04,  8.22858852e+02,  1.48155340e+04,
         1.48181371e+04,  1.46832084e+04,  1.46613820e+04,
         1.4

In [82]:
for i, sample in enumerate(test):
    print(i, sample)
    break

0 (<tf.Tensor: shape=(5, 41), dtype=float64, numpy=
array([[ 1.47580100e+04,  1.48535300e+04,  1.46600000e+04,
         1.48200000e+04,  7.88317514e+02,  1.47524000e+04,
         1.47231707e+04,  4.22379865e+03,  1.45195770e+04,
         1.45191439e+04,  2.00180952e+05,  1.42262813e+04,
         1.43346345e+04,  3.20092987e+05,  1.40165645e+04,
         1.41947771e+04,  3.77744012e+05,  1.36303472e+04,
         1.36303472e+04,  2.75612835e+05,  3.75824654e+02,
         8.81958599e+01,  2.87628794e+02,  7.17877775e+01,
         7.43823419e+01,  7.65426702e+01,  6.51491208e+01,
         6.51070528e+01, -3.23025363e+01,  1.46361410e+04,
         1.47524000e+04,  1.48686590e+04,  1.57613680e+00,
         7.90730174e-01,  3.07759367e-03,  1.00000000e+00,
         2.00000000e+00,  2.69796771e-01,  9.62917287e-01,
         8.66025404e-01, -5.00000000e-01],
       [ 1.48479700e+04,  1.51199000e+04,  1.47449900e+04,
         1.50080700e+04,  8.22858852e+02,  1.48155340e+04,
         1.48181371e

In [26]:
for i, batch in enumerate(train_dataset_2):
  if i == 0:
    inputs, targets = batch
    print(inputs.shape)
    print(inputs[0, :, :])
    print(targets[0])
    print(targets.shape)
    break

(5, 41)


2023-08-10 15:07:54.035075: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at strided_slice_op.cc:111 : INVALID_ARGUMENT: Index out of range using input dim 2; input has only 2 dims


InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:CPU:0}} Index out of range using input dim 2; input has only 2 dims [Op:StridedSlice] name: strided_slice/

In [21]:
for i, batch in enumerate(train_dataset_2):
  if i == 0:
    inputs, targets = batch
    print(inputs.shape)
    print(inputs[1, :, :])
    print(targets[1])
    print(targets.shape)
    break

(128, 5, 41)
tf.Tensor(
[[ 1.48479700e+04  1.51199000e+04  1.47449900e+04  1.50080700e+04
   8.22858852e+02  1.48155340e+04  1.48181371e+04  1.46832084e+04
   1.46613820e+04  1.46080396e+04  1.08343465e+05  1.43274860e+04
   1.44188139e+04  3.14053526e+05  1.41041690e+04  1.42722336e+04
   3.90959981e+05  1.36599284e+04  1.36843755e+04  3.13247498e+05
   3.93305012e+02  8.45409742e+01  3.08764038e+02  7.45019125e+01
   7.77678242e+01  8.18523785e+01  7.02452724e+01  6.69520029e+01
  -2.32352178e+01  1.45987708e+04  1.48155340e+04  1.50322972e+04
   2.92616059e+00  9.44116060e-01  1.26902834e-02  2.00000000e+00
   2.00000000e+00  5.19583950e-01  8.54419405e-01  8.66025404e-01
  -5.00000000e-01]
 [ 1.50080700e+04  1.52999900e+04  1.47500000e+04  1.48184900e+04
   1.03118861e+03  1.48192400e+04  1.48182547e+04  1.46075875e+04
   1.47652310e+04  1.46463033e+04  1.27881921e+04  1.44161160e+04
   1.44687734e+04  2.72643817e+05  1.41779435e+04  1.43242580e+04
   3.81592755e+05  1.36922370e+04

In [24]:
test = train_dataset_2.filter(lambda x,y: x[1] < 3)

ValueError: Invalid `predicate`. `predicate` must return a `tf.bool` scalar tensor, but its return type is TensorSpec(shape=(None, 41), dtype=tf.bool, name=None).

In [12]:
import importlib
build_model = getattr(importlib.import_module(f'ml_investing_wne.tf_models.lstm'),'build_model')
model = build_model(input_shape=(10, 41), nb_classes=config.nb_classes)

2023-07-02 09:47:34.844791: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-07-02 09:47:34.846016: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-07-02 09:47:34.846873: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

In [13]:
model.fit(train_dataset_2, epochs=1, verbose=2)

2023-07-02 09:47:36.873650: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-07-02 09:47:36.875030: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-07-02 09:47:36.876070: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

348/348 - 44s - loss: 0.6950 - accuracy: 0.5074 - 44s/epoch - 128ms/step


In [14]:
y_pred = model.predict(train_dataset_2)

2023-07-02 09:49:19.063328: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-07-02 09:49:19.064814: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-07-02 09:49:19.065663: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

348/348 [==============================] - 14s 39ms/step


In [18]:
y_pred

array([[0.99999994],
       [0.99999994],
       [0.99999994],
       ...,
       [1.        ],
       [1.        ],
       [1.        ]], dtype=float32)

In [46]:
y_pred.shape

(44468, 1)

In [65]:
import pandas as pd

In [66]:
y_pred = pd.DataFrame(y_pred, columns=['y_pred'])
y_pred

y_pred
0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
...       ...
44463     1.0
44464     1.0
44465     1.0
44466     1.0
44467     1.0

[44468 rows x 1 columns]

In [43]:
date_index_dataset = tf.keras.utils.timeseries_dataset_from_array(train_examples[:-sequence_length], targets=date_index.values[sequence_length-1:, 0].astype(int),
                                                            sequence_length=sequence_length, sequence_stride=1, batch_size=128)

In [52]:

for i, batch in enumerate(date_index_dataset):
    if i == 0:
        indices = batch[1].numpy()
    else:
        indices =  np.concatenate((indices, batch[1].numpy()), axis=0)
print(indices.shape)

(44468,)


index            datetime
0          9 2018-01-03 10:00:00
1         10 2018-01-03 11:00:00
2         11 2018-01-03 12:00:00
3         12 2018-01-03 13:00:00
4         13 2018-01-03 14:00:00
...      ...                 ...
44463  44472 2023-01-31 07:00:00
44464  44473 2023-01-31 08:00:00
44465  44474 2023-01-31 09:00:00
44466  44475 2023-01-31 10:00:00
44467  44476 2023-01-31 11:00:00

[44468 rows x 2 columns]

In [71]:
y_pred_with_index = pd.concat([y_pred, date_index.iloc[indices].reset_index(drop=True)], axis=1) 
y_pred_with_index

y_pred  index            datetime
0         1.0      9 2018-01-03 10:00:00
1         1.0     10 2018-01-03 11:00:00
2         1.0     11 2018-01-03 12:00:00
3         1.0     12 2018-01-03 13:00:00
4         1.0     13 2018-01-03 14:00:00
...       ...    ...                 ...
44463     1.0  44472 2023-01-31 07:00:00
44464     1.0  44473 2023-01-31 08:00:00
44465     1.0  44474 2023-01-31 09:00:00
44466     1.0  44475 2023-01-31 10:00:00
44467     1.0  44476 2023-01-31 11:00:00

[44468 rows x 3 columns]

In [38]:
train_examples.shape

(44487, 41)

In [40]:
targets

array([1, 0, 1, ..., 0, 0, 1])

In [ ]:
train_dataset_2 = tf.keras.utils.timeseries_dataset_from_array(train_examples[:-sequence_length], targets=train_labels[sequence_length-1:],
                                                            sequence_length=sequence_length, sequence_stride=1, batch_size=128)

In [23]:
y_true = np.array([])  # store true labels
     # iterate over the dataset
for x, label_batch in train_dataset_2:   # use dataset.unbatch() with repeat
     # append true labels
    y_true = np.concatenate((y_true, label_batch.numpy()), axis=0)

In [25]:
y_true.shape

(44468,)

In [19]:
label_batch2 = label_batch.numpy()

In [20]:
np.stack(label_batch.numpy(), label_batch2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [21]:
np.concatenate((label_batch.numpy(), label_batch2), axis=0)

array([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1])