In [1]:
# hide GPU from tensorflow
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

In [2]:
import random
import numpy as np
import tensorflow as tf
import mlflow.keras

from ml_investing_wne import config
from ml_investing_wne.utils import get_logger
from ml_investing_wne.experiment_factory import create_asset, experiment_factory

random.seed(config.seed)
np.random.seed(config.seed)
tf.random.set_seed(config.seed)


In [3]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [4]:
config.currency = 'BTCUSDT'
btc = create_asset()
experiment_btc = experiment_factory(btc).get_experiment()

In [5]:
experiment_btc.df.head(10)


open      high       low     close       volume  \
datetime                                                                   
2018-01-03 01:00:00  14758.01  14853.53  14660.00  14820.00   788.317514   
2018-01-03 02:00:00  14847.97  15119.90  14744.99  15008.07   822.858852   
2018-01-03 03:00:00  15008.07  15299.99  14750.00  14818.49  1031.188608   
2018-01-03 04:00:00  14805.81  15117.56  14795.05  15019.66   781.021342   
2018-01-03 05:00:00  15031.01  15114.98  14900.00  14988.00   860.383177   
2018-01-03 06:00:00  14980.89  15276.13  14858.01  15242.63   908.687696   
2018-01-03 07:00:00  15242.64  15307.56  15130.24  15170.00   661.609852   
2018-01-03 08:00:00  15170.00  15172.99  14900.00  15002.59   895.934758   
2018-01-03 09:00:00  15002.59  15048.00  14440.00  14519.99  1241.904776   
2018-01-03 10:00:00  14501.05  14855.00  14150.00  14455.55  1271.034018   

                       y_pred      SMA_5         EMA_5         VAR_5  \
datetime                                                               
2018-01-03 01:00:00  1.012690  14752.400  14723.170661    4223.79865   
2018-01-03 02:00:00  0.987368  14815.534  14818.137107   14683.20843   
2018-01-03 03:00:00  1.013576  14819.240  14818.254738   14607.58750   
2018-01-03 04:00:00  0.997892  14888.150  14885.389826   13520.53225   
2018-01-03 05:00:00  1.016989  14930.844  14919.593217   10507.18973   
2018-01-03 06:00:00  0.995235  15015.370  15027.272145   22807.41325   
2018-01-03 07:00:00  0.988964  15047.756  15074.848096   27460.63373   
2018-01-03 08:00:00  0.967832  15084.576  15050.762064   13135.26043   
2018-01-03 09:00:00  0.995562  14984.642  14873.838043   79287.57107   
2018-01-03 10:00:00  1.018989  14878.152  14734.408695  135094.18802   

                        SMA_10  ...     BBU_5_2.0  BBB_5_2.0  BBP_5_2.0  \
datetime                        ...                                       
2018-01-03 01:00:00  14519.577  ...  14868.659003   1.576137   0.790730   
2018-01-03 02:00:00  14661.382  ...  15032.297159   2.926161   0.944116   
2018-01-03 03:00:00  14765.231  ...  15035.444255   2.917886   0.498266   
2018-01-03 04:00:00  14809.197  ...  15096.154094   2.794224   0.816124   
2018-01-03 05:00:00  14834.722  ...  15114.209774   2.456201   0.655852   
2018-01-03 06:00:00  14883.885  ...  15285.524997   3.598379   0.920610   
2018-01-03 07:00:00  14931.645  ...  15344.191538   3.939930   0.706190   
2018-01-03 08:00:00  14951.908  ...  15289.595105   2.718261   0.300053   
2018-01-03 09:00:00  14936.396  ...  15488.348489   6.722970   0.038767   
2018-01-03 10:00:00  14904.498  ...  15535.648313   8.838414   0.178628   

                        roc_1  hour  weekday  hour_sin  hour_cos  weekday_sin  \
datetime                                                                        
2018-01-03 01:00:00  0.003078     1        2  0.269797  0.962917     0.866025   
2018-01-03 02:00:00  0.012690     2        2  0.519584  0.854419     0.866025   
2018-01-03 03:00:00 -0.012632     3        2  0.730836  0.682553     0.866025   
2018-01-03 04:00:00  0.013576     4        2  0.887885  0.460065     0.866025   
2018-01-03 05:00:00 -0.002108     5        2  0.979084  0.203456     0.866025   
2018-01-03 06:00:00  0.016989     6        2  0.997669 -0.068242     0.866025   
2018-01-03 07:00:00 -0.004765     7        2  0.942261 -0.334880     0.866025   
2018-01-03 08:00:00 -0.011036     8        2  0.816970 -0.576680     0.866025   
2018-01-03 09:00:00 -0.032168     9        2  0.631088 -0.775711     0.866025   
2018-01-03 10:00:00 -0.004438    10        2  0.398401 -0.917211     0.866025   

                     weekday_cos  
datetime                          
2018-01-03 01:00:00         -0.5  
2018-01-03 02:00:00         -0.5  
2018-01-03 03:00:00         -0.5  
2018-01-03 04:00:00         -0.5  
2018-01-03 05:00:00         -0.5  
2018-01-03 06:00:00         -0.5  
2018-01-03 07:00:00         -0.5  
2018-01-03 08:00:00         -0.5  
2018-01-03 09:00:00    

In [6]:
experiment_btc.df['y_pred'] = [1 if y > 1 else 0 for y in  experiment_btc.df['y_pred']]
train_examples = experiment_btc.df.drop(columns=['y_pred']).values
train_labels = experiment_btc.df['y_pred'].values

In [7]:
date_index = experiment_btc.df.reset_index()
date_index.reset_index(inplace=True)
date_index = date_index[['index', 'datetime']]
date_index

index            datetime
0          0 2018-01-03 01:00:00
1          1 2018-01-03 02:00:00
2          2 2018-01-03 03:00:00
3          3 2018-01-03 04:00:00
4          4 2018-01-03 05:00:00
...      ...                 ...
44482  44482 2023-01-31 17:00:00
44483  44483 2023-01-31 18:00:00
44484  44484 2023-01-31 19:00:00
44485  44485 2023-01-31 20:00:00
44486  44486 2023-01-31 21:00:00

[44487 rows x 2 columns]

In [8]:
experiment_btc.df.head(10)

open      high       low     close       volume  \
datetime                                                                   
2018-01-03 01:00:00  14758.01  14853.53  14660.00  14820.00   788.317514   
2018-01-03 02:00:00  14847.97  15119.90  14744.99  15008.07   822.858852   
2018-01-03 03:00:00  15008.07  15299.99  14750.00  14818.49  1031.188608   
2018-01-03 04:00:00  14805.81  15117.56  14795.05  15019.66   781.021342   
2018-01-03 05:00:00  15031.01  15114.98  14900.00  14988.00   860.383177   
2018-01-03 06:00:00  14980.89  15276.13  14858.01  15242.63   908.687696   
2018-01-03 07:00:00  15242.64  15307.56  15130.24  15170.00   661.609852   
2018-01-03 08:00:00  15170.00  15172.99  14900.00  15002.59   895.934758   
2018-01-03 09:00:00  15002.59  15048.00  14440.00  14519.99  1241.904776   
2018-01-03 10:00:00  14501.05  14855.00  14150.00  14455.55  1271.034018   

                     y_pred      SMA_5         EMA_5         VAR_5     SMA_10  \
datetime                                                                        
2018-01-03 01:00:00       1  14752.400  14723.170661    4223.79865  14519.577   
2018-01-03 02:00:00       0  14815.534  14818.137107   14683.20843  14661.382   
2018-01-03 03:00:00       1  14819.240  14818.254738   14607.58750  14765.231   
2018-01-03 04:00:00       0  14888.150  14885.389826   13520.53225  14809.197   
2018-01-03 05:00:00       1  14930.844  14919.593217   10507.18973  14834.722   
2018-01-03 06:00:00       0  15015.370  15027.272145   22807.41325  14883.885   
2018-01-03 07:00:00       0  15047.756  15074.848096   27460.63373  14931.645   
2018-01-03 08:00:00       0  15084.576  15050.762064   13135.26043  14951.908   
2018-01-03 09:00:00       0  14984.642  14873.838043   79287.57107  14936.396   
2018-01-03 10:00:00       1  14878.152  14734.408695  135094.18802  14904.498   

                     ...     BBU_5_2.0  BBB_5_2.0  BBP_5_2.0     roc_1  hour  \
datetime             ...                                                       
2018-01-03 01:00:00  ...  14868.659003   1.576137   0.790730  0.003078     1   
2018-01-03 02:00:00  ...  15032.297159   2.926161   0.944116  0.012690     2   
2018-01-03 03:00:00  ...  15035.444255   2.917886   0.498266 -0.012632     3   
2018-01-03 04:00:00  ...  15096.154094   2.794224   0.816124  0.013576     4   
2018-01-03 05:00:00  ...  15114.209774   2.456201   0.655852 -0.002108     5   
2018-01-03 06:00:00  ...  15285.524997   3.598379   0.920610  0.016989     6   
2018-01-03 07:00:00  ...  15344.191538   3.939930   0.706190 -0.004765     7   
2018-01-03 08:00:00  ...  15289.595105   2.718261   0.300053 -0.011036     8   
2018-01-03 09:00:00  ...  15488.348489   6.722970   0.038767 -0.032168     9   
2018-01-03 10:00:00  ...  15535.648313   8.838414   0.178628 -0.004438    10   

                     weekday  hour_sin  hour_cos  weekday_sin  weekday_cos  
datetime                                                                    
2018-01-03 01:00:00        2  0.269797  0.962917     0.866025         -0.5  
2018-01-03 02:00:00        2  0.519584  0.854419     0.866025         -0.5  
2018-01-03 03:00:00        2  0.730836  0.682553     0.866025         -0.5  
2018-01-03 04:00:00        2  0.887885  0.460065     0.866025         -0.5  
2018-01-03 05:00:00        2  0.979084  0.203456     0.866025         -0.5  
2018-01-03 06:00:00        2  0.997669 -0.068242     0.866025         -0.5  
2018-01-03 07:00:00        2  0.942261 -0.334880     0.866025         -0.5  
2018-01-03 08:00:00        2  0.816970 -0.576680     0.866025         -0.5  
2018-01-03 09:00:00        2  0.631088 -0.775711     0.866025         -0.5  
2018-01-03 10:00:00        2  0.398401 -0.917211     0.866025         -0.5  

[10 rows x 42 columns]

In [11]:
from tensorflow.keras.utils import to_categorical

In [10]:
train_labels[sequence_length-1:]

array([1, 0, 1, ..., 0, 0, 1])

In [12]:
to_categorical(train_labels[sequence_length-1:])

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [9]:
sequence_length=10

In [13]:
train_dataset_2 = tf.keras.utils.timeseries_dataset_from_array(train_examples[:-sequence_length], targets=to_categorical(train_labels[sequence_length-1:]),
                                                            sequence_length=sequence_length, sequence_stride=1, batch_size=128)

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



In [14]:
for i, batch in enumerate(train_dataset_2):
  if i == 0:
    inputs, targets = batch
    print(inputs.shape)
    print(inputs[0, :, :])
    print(targets[0])
    print(targets.shape)
    break

(128, 10, 41)
tf.Tensor(
[[ 1.47580100e+04  1.48535300e+04  1.46600000e+04  1.48200000e+04
   7.88317514e+02  1.47524000e+04  1.47231707e+04  4.22379865e+03
   1.45195770e+04  1.45191439e+04  2.00180952e+05  1.42262813e+04
   1.43346345e+04  3.20092987e+05  1.40165645e+04  1.41947771e+04
   3.77744012e+05  1.36303472e+04  1.36303472e+04  2.75612835e+05
   3.75824654e+02  8.81958599e+01  2.87628794e+02  7.17877775e+01
   7.43823419e+01  7.65426702e+01  6.51491208e+01  6.51070528e+01
  -3.23025363e+01  1.46361410e+04  1.47524000e+04  1.48686590e+04
   1.57613680e+00  7.90730174e-01  3.07759367e-03  1.00000000e+00
   2.00000000e+00  2.69796771e-01  9.62917287e-01  8.66025404e-01
  -5.00000000e-01]
 [ 1.48479700e+04  1.51199000e+04  1.47449900e+04  1.50080700e+04
   8.22858852e+02  1.48155340e+04  1.48181371e+04  1.46832084e+04
   1.46613820e+04  1.46080396e+04  1.08343465e+05  1.43274860e+04
   1.44188139e+04  3.14053526e+05  1.41041690e+04  1.42722336e+04
   3.90959981e+05  1.36599284e+0

In [15]:
for i, batch in enumerate(train_dataset_2):
  if i == 0:
    inputs, targets = batch
    print(inputs.shape)
    print(inputs[1, :, :])
    print(targets[1])
    print(targets.shape)
    break

(128, 10, 41)
tf.Tensor(
[[ 1.48479700e+04  1.51199000e+04  1.47449900e+04  1.50080700e+04
   8.22858852e+02  1.48155340e+04  1.48181371e+04  1.46832084e+04
   1.46613820e+04  1.46080396e+04  1.08343465e+05  1.43274860e+04
   1.44188139e+04  3.14053526e+05  1.41041690e+04  1.42722336e+04
   3.90959981e+05  1.36599284e+04  1.36843755e+04  3.13247498e+05
   3.93305012e+02  8.45409742e+01  3.08764038e+02  7.45019125e+01
   7.77678242e+01  8.18523785e+01  7.02452724e+01  6.69520029e+01
  -2.32352178e+01  1.45987708e+04  1.48155340e+04  1.50322972e+04
   2.92616059e+00  9.44116060e-01  1.26902834e-02  2.00000000e+00
   2.00000000e+00  5.19583950e-01  8.54419405e-01  8.66025404e-01
  -5.00000000e-01]
 [ 1.50080700e+04  1.52999900e+04  1.47500000e+04  1.48184900e+04
   1.03118861e+03  1.48192400e+04  1.48182547e+04  1.46075875e+04
   1.47652310e+04  1.46463033e+04  1.27881921e+04  1.44161160e+04
   1.44687734e+04  2.72643817e+05  1.41779435e+04  1.43242580e+04
   3.81592755e+05  1.36922370e+0

In [12]:
import importlib
build_model = getattr(importlib.import_module(f'ml_investing_wne.tf_models.lstm'),'build_model')
model = build_model(input_shape=(10, 41), nb_classes=config.nb_classes)

2023-07-02 09:47:34.844791: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-07-02 09:47:34.846016: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-07-02 09:47:34.846873: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

In [13]:
model.fit(train_dataset_2, epochs=1, verbose=2)

2023-07-02 09:47:36.873650: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-07-02 09:47:36.875030: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-07-02 09:47:36.876070: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

348/348 - 44s - loss: 0.6950 - accuracy: 0.5074 - 44s/epoch - 128ms/step


In [14]:
y_pred = model.predict(train_dataset_2)

2023-07-02 09:49:19.063328: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-07-02 09:49:19.064814: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-07-02 09:49:19.065663: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

348/348 [==============================] - 14s 39ms/step


In [18]:
y_pred

array([[0.99999994],
       [0.99999994],
       [0.99999994],
       ...,
       [1.        ],
       [1.        ],
       [1.        ]], dtype=float32)

In [46]:
y_pred.shape

(44468, 1)

In [65]:
import pandas as pd

In [66]:
y_pred = pd.DataFrame(y_pred, columns=['y_pred'])
y_pred

y_pred
0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
...       ...
44463     1.0
44464     1.0
44465     1.0
44466     1.0
44467     1.0

[44468 rows x 1 columns]

In [43]:
date_index_dataset = tf.keras.utils.timeseries_dataset_from_array(train_examples[:-sequence_length], targets=date_index.values[sequence_length-1:, 0].astype(int),
                                                            sequence_length=sequence_length, sequence_stride=1, batch_size=128)

In [52]:

for i, batch in enumerate(date_index_dataset):
    if i == 0:
        indices = batch[1].numpy()
    else:
        indices =  np.concatenate((indices, batch[1].numpy()), axis=0)
print(indices.shape)

(44468,)


index            datetime
0          9 2018-01-03 10:00:00
1         10 2018-01-03 11:00:00
2         11 2018-01-03 12:00:00
3         12 2018-01-03 13:00:00
4         13 2018-01-03 14:00:00
...      ...                 ...
44463  44472 2023-01-31 07:00:00
44464  44473 2023-01-31 08:00:00
44465  44474 2023-01-31 09:00:00
44466  44475 2023-01-31 10:00:00
44467  44476 2023-01-31 11:00:00

[44468 rows x 2 columns]

In [71]:
y_pred_with_index = pd.concat([y_pred, date_index.iloc[indices].reset_index(drop=True)], axis=1) 
y_pred_with_index

y_pred  index            datetime
0         1.0      9 2018-01-03 10:00:00
1         1.0     10 2018-01-03 11:00:00
2         1.0     11 2018-01-03 12:00:00
3         1.0     12 2018-01-03 13:00:00
4         1.0     13 2018-01-03 14:00:00
...       ...    ...                 ...
44463     1.0  44472 2023-01-31 07:00:00
44464     1.0  44473 2023-01-31 08:00:00
44465     1.0  44474 2023-01-31 09:00:00
44466     1.0  44475 2023-01-31 10:00:00
44467     1.0  44476 2023-01-31 11:00:00

[44468 rows x 3 columns]

In [38]:
train_examples.shape

(44487, 41)

In [40]:
targets

array([1, 0, 1, ..., 0, 0, 1])

In [ ]:
train_dataset_2 = tf.keras.utils.timeseries_dataset_from_array(train_examples[:-sequence_length], targets=train_labels[sequence_length-1:],
                                                            sequence_length=sequence_length, sequence_stride=1, batch_size=128)

In [23]:
y_true = np.array([])  # store true labels
     # iterate over the dataset
for x, label_batch in train_dataset_2:   # use dataset.unbatch() with repeat
     # append true labels
    y_true = np.concatenate((y_true, label_batch.numpy()), axis=0)

In [25]:
y_true.shape

(44468,)

In [19]:
label_batch2 = label_batch.numpy()

In [20]:
np.stack(label_batch.numpy(), label_batch2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [21]:
np.concatenate((label_batch.numpy(), label_batch2), axis=0)

array([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1])